name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install arm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: armv7-unknown-linux-gnueabihf
    - name: Install arm gcc
      run: sudo apt install gcc-arm-linux-gnueabihf
    - name: Build
      run: cargo build --verbose --release --target=armv7-unknown-linux-gnueabihf
    - name: Run tests
      run: cargo test --verbose
